-- < OLYMPIC 데이터베이스 >

-- 테이블 지우기 생성
DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;

-- 국가 테이블(NATION_TBL) 생성
CREATE TABLE NATION_TBL (
    N_CODE          NUMBER   (3)       NOT NULL     -- NUMBER(3) : 0 ~ 999 , 숫자만 적으면 정밀도로 친다.
  , N_NAME          VARCHAR2 (30 BYTE) NOT NULL
  , N_PARTI_PERSON  NUMBER
  , N_PARTI_EVENT   NUMBER
  , N_PREV_RANK     NUMBER
  , N_CURR_RANK     NUMBER
  
);

-- 종목 테이블(EVENT_TBL) 생성
CREATE TABLE EVENT_TBL (
    E_CODE         NUMBER              NOT NULL
  , E_NAME         VARCHAR2 (30 BYTE)  NOT NULL
  , E_FIRST_YEAR   NUMBER   (4)         -- NUMBER(4) : 0 ~ 9999
  , E_INFO         VARCHAR2 (100 BYTE)
  
);

-- 선수 테이블(PLAYER_TBL) 생성
CREATE TABLE PLAYER_TBL (
    P_CODE NUMBER   (3)         NOT NULL
  , P_NAME VARCHAR2 (30 BYTE)   NOT NULL
  , N_CODE NUMBER   (3)         NOT NULL
  , E_CODE NUMBER               NOT NULL
  , P_RANK NUMBER
  , P_AGE  NUMBER   (3)
 
);

-- 일정 테이블(SCHEDULE_TBL) 생성
CREATE TABLE SCHEDULE_TBL (
    S_NO         NUMBER   (3)     NOT NULL
  , N_CODE       NUMBER   (3)
  , E_CODE       NUMBER
  , S_START_DATE DATE
  , S_END_DATE   DATE
  , S_INFO       VARCHAR2 (100 BYTE)
 
);

-- 기본키 추가하기
ALTER TABLE NATION_TBL ADD CONSTRAINT PK_NATION PRIMARY KEY(N_CODE);
ALTER TABLE EVENT_TBL ADD CONSTRAINT PK_EVENT PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_PLAYER PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY(S_NO);

-- 외래키 추가하기
ALTER TABLE PLAYER_TBL   ADD CONSTRAINT FK_NATION_PLAYER FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE CASCADE;  -- PLAYER_TBL의 N_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능하다.
ALTER TABLE PLAYER_TBL   ADD CONSTRAINT FK_EVENT_PLAYER FOREIGN KEY(E_CODE)  REFERENCES EVENT_TBL(E_CODE)  ON DELETE CASCADE;  -- EVENT_TBL의 E_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능하다.
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_NATION_SCHEDULE FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE SET NULL;  -- ON DELETE CASCADE도 가능하다.
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_EVENT_SCHEDULE FOREIGN KEY(E_CODE)  REFERENCES EVENT_TBL(E_CODE)  ON DELETE SET NULL;  -- ON DELETE CASCADE도 가능하다.

--모델화(이미지화)시켰을 때, 삼발이 위에 동그라미는 삭제하고 NULL값으로 채우겠다는 옵션(ON DELETE SET NULL)이다. , X표시는 삭제표시.
--모델화에서 점선과 실선은 외래키가 NOT NULL 로 되어있으면 실선, 외래키가 NULL이면 점선으로 나온다.
--마름모는 관계 표시. 빨간점 NOT NULL, 황금열쇠:외래키 , 열쇠:기본키, 삼발이가 M , 화살표쪽이 1  .  1:M 일대다관계.  


-- 국가 테이블의 기본키 삭제하기
-- 국가 테이블의 기본키를 참조하는 외래키를 먼저 삭제해야 한다.
ALTER TABLE PLAYER_TBL DROP CONSTRAINT FK_NATION_PLAYER;
ALTER TABLE SCHEDULE_TBL DROP CONSTRAINT FK_NATION_SCHEDULE;
ALTER TABLE NATION_TBL DROP CONSTRAINT PK_NATION
-- *테이블 삭제 순서와 같음(외래키부터 지우고, 기본키 지워야 가능)


-- 선수 테이블의 FK_EVENT_PLAYER 외래키 일시중지하기
ALTER TABLE PLAYER_TBL DISABLE CONSTRAINT FK_EVENT_PLAYER;

-- 선수 테이블의 FK_EVENT_PLAYER 외래키 다시시작하기
ALTER TABLE PLAYER_TBL ENABLE CONSTRAINT FK_EVENT_PLAYER;




