-- < 데이터베이스 오브젝트 설계 예제문 >

--삭제는 생성의 역순
DROP TABLE PROCEEDING_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;


-- 부서 테이블
CREATE TABLE DEPARTMENT_TBL (
    DEPT_NO         VARCHAR2(15 BYTE) NOT NULL
  , DEPT_NAME       VARCHAR2(30 BYTE) NULL
  , DEPT_LOCATION   VARCHAR2(50 BYTE) NULL
  , CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NO)
);


-- 사원 테이블 (부서테이블과 FK)
CREATE TABLE EMPLOYEE_TBL (
    EMP_NO     NUMBER             NOT NULL     
  , DEPT_NO    VARCHAR2 (15 BYTE) NULL           
  , POSITION   CHAR     (10 BYTE) NULL
  , NAME       VARCHAR2 (15 BYTE) NULL
  , HIRE_DATE  DATE               NULL
  , SALARY     NUMBER             NULL
  , CONSTRAINT PK_EMP  PRIMARY KEY(EMP_NO)
  , CONSTRAINT FK_DEPT FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL --부서가 삭제되면 사원들의 해당 부서 정보만 NULL 처리한다.
);


-- 프로젝트 테이블
CREATE TABLE PROJECT_TBL (
    PJT_NO      NUMBER             NOT NULL 
  , PJT_NAME    VARCHAR2(30 BYTE)  NULL
  , BEGIN_DATE  DATE               NULL
  , END_DATE    DATE               NULL
  , CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO)
);


-- 프로젝트진행 테이블 (사원,프로젝트 테이블과 FK)
CREATE TABLE PROCEEDING_TBL (
    PCD_NO     NUMBER NOT NULL 
  , EMP_NO     NUMBER NOT NULL        
  , PJT_NO     NUMBER NOT NULL       
  , PJT_STATE  NUMBER NOT NULL
  , CONSTRAINT PK_PCD PRIMARY KEY(PCD_NO)
  , CONSTRAINT FK_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TBL(EMP_NO) ON DELETE CASCADE -- 사원이 삭제되면 프로젝트진행 명단에서 함께 삭제된다.
  , CONSTRAINT FK_PJT FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO) ON DELETE CASCADE -- 프로젝트가 삭제되면 프로젝트진행 명단에서 함께 삭제된다.
);
--EMP와 PJT_NO 는 표에 NOT NULL 값이기 때문에 어차피 NULL값이 들어갈 수가 없어서 ON DELETE CASCADE 를 써주면 된다.















