-- <수강신청 데이터베이스>  : 학생에 교수번호가 있으니 교수부터 만들어야 한다.
-- 이번에는 콤마(,) 전부 찍어서 에러났음. / 테이블마다 칼럼제목값을 INSERT 로 다 만들어 주어야 칼럼안에 값을 INSERT 입력값을 배치할 수 있음.


-- 테이블 지우기
DROP TABLE LECTURE_TBL;
DROP TABLE ENROLL_TBL;
DROP TABLE STUDENT_TBL;
DROP TABLE COURSE_TBL;
DROP TABLE PROFESSOR_TBL;


-- 교수 테이블(PROFESSOR_TBL) 생성
CREATE TABLE PROFESSOR_TBL (
    PRO_NO   VARCHAR2(13 BYTE) NOT NULL
  , PRO_NAME VARCHAR2(30 BYTE) NOT NULL
  , PRO_COUR VARCHAR2(30 BYTE) NOT NULL
);

-- 과목 테이블(COURSE_TBL) 생성
CREATE TABLE COURSE_TBL (
    COR_NO     NUMBER  (4)        NOT NULL
  , COR_NAME   VARCHAR2(20 BYTE)  NOT NULL
  , COR_SCORE  NUMBER             NOT NULL
);

-- 학생 테이블(STUDENT_TBL) 생성
CREATE TABLE STUDENT_TBL (
    STU_NO  NUMBER  (4)        NOT NULL
  , NAME    VARCHAR2(30 BYTE)  NOT NULL
  , ADDRESS VARCHAR2(30 BYTE)  NOT NULL
  , GRADE   NUMBER             NOT NULL
  , PRO_NO  VARCHAR2(13 BYTE)  NOT NULL
);

-- 수강신청 테이블(ENROLL_TBL) 생성  => 시퀀스 필요
CREATE TABLE ENROLL_TBL (
    ENROLL_NO NUMBER(4) NOT NULL
  , STU_NO    NUMBER(4) NOT NULL
  , COR_NO    NUMBER(4) NOT NULL
  , SIGN_DATE DATE      NOT NULL
);

-- 강의 테이블(LECTURE_TBL) 생성 => 시퀀스 필요
CREATE TABLE LECTURE_TBL (
    LEC_NO      NUMBER            NOT NULL
  , PRO_NO      VARCHAR2(13 BYTE) NOT NULL
  , LEC_ENROLL  NUMBER(4)             NOT NULL
  , LEC_NAME    VARCHAR2(20 BYTE) NOT NULL
  , LEC_ROOM    VARCHAR2(20 BYTE) NOT NULL
);


-- 기본키 추가
ALTER TABLE STUDENT_TBL   ADD CONSTRAINT PK_STU    PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR_TBL ADD CONSTRAINT PK_PRO    PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE_TBL    ADD CONSTRAINT PK_COR    PRIMARY KEY(COR_NO);
ALTER TABLE LECTURE_TBL   ADD CONSTRAINT PK_LEC    PRIMARY KEY(LEC_NO);
ALTER TABLE ENROLL_TBL    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENROLL_NO);

-- 외래키 추가
ALTER TABLE ENROLL_TBL    ADD CONSTRAINT FK_STU_STU FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO) ON DELETE CASCADE;
ALTER TABLE LECTURE_TBL   ADD CONSTRAINT FK_ENROLL  FOREIGN KEY(LEC_ENROLL) REFERENCES ENROLL_TBL(ENROLL_NO) ON DELETE CASCADE;
ALTER TABLE LECTURE_TBL   ADD CONSTRAINT FK_PRO_PRO FOREIGN KEY(PRO_NO) REFERENCES PROFESSOR_TBL(PRO_NO) ON DELETE CASCADE;
ALTER TABLE ENROLL_TBL    ADD CONSTRAINT FK_COR_COR FOREIGN KEY(COR_NO) REFERENCES COURSE_TBL(COR_NO) ON DELETE CASCADE;


-- 데이터 삽입 ( * 테이블 만들 때 실제로 칼럼에 이름이 생략되어있다. 그래서 INSERT로 이름 만들어주고 하는 것)
-- 데이터 삽입해야 하는 해당 테이블에는 데이터 삽입해줘야 함.

-- 교수 테이블(PROFESSOR_TBL) 데이터 입력
INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_COUR) VALUES('1111','이순신','거북선운용');
INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_COUR) VALUES('1112','세종대왕','한글활용');
INSERT INTO PROFESSOR_TBL(PRO_NO, PRO_NAME, PRO_COUR) VALUES('1113','돌하르방','제주살이');

-- 과목 테이블(COURSE_TBL) 데이터 입력
INSERT INTO COURSE_TBL(COR_NO, COR_NAME, COR_SCORE) VALUES('2222','거북선운용법','3');
INSERT INTO COURSE_TBL(COR_NO, COR_NAME, COR_SCORE) VALUES('2223','한글활용법','4');
INSERT INTO COURSE_TBL(COR_NO, COR_NAME, COR_SCORE) VALUES('2224','제주살이법','5');

-- 학생 테이블(STUDENT_TBL) 데이터 입력
INSERT INTO STUDENT_TBL(STU_NO, NAME, ADDRESS, GRADE, PRO_NO) VALUES(9991, '박일', '서울',   1, '010-1234-5678');
INSERT INTO STUDENT_TBL(STU_NO, NAME, ADDRESS, GRADE, PRO_NO) VALUES(9992, '박이', '대구',   2, '010-2345-6789');
INSERT INTO STUDENT_TBL(STU_NO, NAME, ADDRESS, GRADE, PRO_NO) VALUES(9993, '박삼', '부산',   3, '010-3456-7890');
INSERT INTO STUDENT_TBL(STU_NO, NAME, ADDRESS, GRADE, PRO_NO) VALUES(9994, '박사', '제주도', 4, '010-4567-8901');

-- 수강신청 테이블(ENROLL_TBL) 데이터 입력
INSERT INTO ENROLL_TBL(ENROLL_NO, STU_NO, COR_NO, SIGN_DATE) VALUES(104, '001', '서울',   1, '010/1234/5678');


---수강신청 테이블(ENROLL_TBL) 시퀀스---
DROP SEQUENCE ENROLL_SEQ;
CREATE SEQUENCE ENROLL_SEQ ORDER;

INSERT INTO ENROLL_TBL(ENROLL_NO, STU_NO, COR_NO, SIGN_DATE) VALUES(ENROLL_SEQ.NEXTVAL, '001', '2222', '23-07-14');


---강의 테이블(LECTURE_TBL) 시퀀스---
DROP SEQUENCE LEC_SEQ;
CREATE SEQUENCE LEC_SEQ ORDER;

INSERT INTO LECTURE_TBL(LEC_NO, PRO_NO, LEC_ENROLL, LEC_NAME, LEC_ROOM) VALUES(LEC_SEQ.NEXTVAL, '1112', 7777, 'DB미래', '개발1실');


COMMIT;